
LightsTab ( 13
	LightsTabEntry (
		"Red Light"
		colour ( 240 195 30 39 )
	)
	LightsTabEntry (
		"Amber Light"
		colour ( 255 255 155 0 )
	)
	LightsTabEntry (
		"Green Light"
		colour ( 255 79 186 130 )
	)
	LightsTabEntry (
		"White Light"
		colour ( 255 255 255 191 )
	)
	LightsTabEntry (
		"Violet Light"
		colour ( 255 96 128 255 )
	)
	LightsTabEntry (
		"White Light C"
		colour ( 255 255 255 255 )
	)
	LightsTabEntry (
		"RC Light"
		colour ( 255 150 100 100 )
	)
	LightsTabEntry (
		"Blue Light"
		colour ( 255 0 120 255 )
	)
	LightsTabEntry (
		"Green LED Light"
		colour ( 255 53 255 0 )
	)
	LightsTabEntry (
		"Amber LED Light"
		colour ( 255 255 217 0 )
	)
	LightsTabEntry (
		"Red LED Light"
		colour ( 255 255 35 0 )
	)
	LightsTabEntry (
		"White LED Light"
		colour ( 255 255 255 237 )
	)
	LightsTabEntry (
		"Blue LED Light"
		colour ( 255 0 110 255 )
	)
)
