
SignalSubObj ( 1
	"DECOR"
	"Reposo Anuncio de Parada"
	SigSubType ( DECOR )
	SignalFlags ( OPTIONAL )
)
SignalSubObj ( 2
	"DECOR"
	"Reposo Via Libre"
	SigSubType ( DECOR )
	SignalFlags ( OPTIONAL )
)
SignalSubObj ( 3
	"DECOR"
	"Tipo de señalizacion 200"
	SigSubType ( DECOR )
	SignalFlags ( OPTIONAL )
)
SignalSubObj ( 4
	"DECOR"
	"Anuncio de Parada inmediata"
	SigSubType ( DECOR )
	SignalFlags ( OPTIONAL )
)
SignalSubObj ( 5
	"DECOR5"
	"Señal permisiva"
	SigSubType ( DECOR )
	SignalFlags ( OPTIONAL )
)
SignalSubObj ( 6
	"DECOR"
	"Señal intermedia"
	SigSubType ( DECOR )
	SignalFlags ( OPTIONAL )
)
SignalSubObj ( 7
	"DECOR"
	"Señal preavanzada"
	SigSubType ( DECOR )
	SignalFlags ( OPTIONAL )
)
SignalSubObj ( 8
	"DECOR"
	"Señal avanzada"
	SigSubType ( DECOR )
	SignalFlags ( OPTIONAL )
)
SignalSubObj ( 9
	"DECOR"
	"Señal de entrada"
	SigSubType ( DECOR )
	SignalFlags ( OPTIONAL )
)
SignalSubObj ( 10
	"DECOR"
	"Señal de salida"
	SigSubType ( DECOR )
	SignalFlags ( OPTIONAL )
)
SignalSubObj ( 11
	"DECOR"
	"Señal de proteccion"
	SigSubType ( DECOR )
	SignalFlags ( OPTIONAL )
)
SignalSubObj ( 12
	"DECOR"
	"Señal de liberacion"
	SigSubType ( DECOR )
	SignalFlags ( OPTIONAL )
)
SignalSubObj ( 13
	"DECOR"
	"Señal de BSL"
	SigSubType ( DECOR )
	SignalFlags ( OPTIONAL )
)
SignalSubObj ( 14
	"DECOR"
	"Señal de LZB"
	SigSubType ( DECOR )
	SignalFlags ( OPTIONAL )
)
SignalSubObj ( 15
	"DECOR"
	"Señal de BLA"
	SigSubType ( DECOR )
	SignalFlags ( OPTIONAL )
)
