
SignalSubObj ( 1
    "DECOR1"
    "Sumar 50m"
    SigSubType ( DECOR )
    SignalFlags ( OPTIONAL )
)
SignalSubObj ( 2
    "DECOR1"
    "Sumar 100m"
    SigSubType ( DECOR )
    SignalFlags ( OPTIONAL )
)
SignalSubObj ( 3
    "DECOR1"
    "Sumar 200m"
    SigSubType ( DECOR )
    SignalFlags ( OPTIONAL )
)
SignalSubObj ( 4
    "DECOR2"
    "Sumar 400m"
    SigSubType ( DECOR )
    SignalFlags ( OPTIONAL )
)
SignalSubObj ( 5
    "DECOR3"
    "Sumar 800m"
    SigSubType ( DECOR )
    SignalFlags ( OPTIONAL )
)
SignalSubObj ( 6
    "DECOR4"
    "Sumar 1600m"
    SigSubType ( DECOR )
    SignalFlags ( OPTIONAL )
)
