
SignalSubObj ( 1
    "DECOR1"
    "+1"
    SigSubType ( DECOR )
    SignalFlags ( OPTIONAL )
)
SignalSubObj ( 2
    "DECOR2"
    "+2"
    SigSubType ( DECOR )
    SignalFlags ( OPTIONAL )
)
SignalSubObj ( 3
    "DECOR3"
    "+4"
    SigSubType ( DECOR )
    SignalFlags ( OPTIONAL )
)
SignalSubObj ( 4
    "DECOR4"
    "+8"
    SigSubType ( DECOR )
    SignalFlags ( OPTIONAL )
)
SignalSubObj ( 5
    "DECOR5"
    "+16"
    SigSubType ( DECOR )
    SignalFlags ( OPTIONAL )
)
