
SignalShape (
	"PN.s"
	"RENFE Senal Paso a nivel"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "PN" )
		)
	)
)

SignalShape (
	"Pedal_PN.s"
	"RENFE Pedal Paso a nivel"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "OPEDALPN" )
		)
	)
)

SignalShape (
	"OPN.s"
	"RENFE Adicional SPN"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "OPN" )
		)
	)
)

SignalShape (
	"OLPN.s"
	"RENFE Senal Oculta Paso a nivel"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "OLPN" )
		)
	)
)

SignalShape (
	"ESRNIndSal.s"
	"RENFE Panel Indicadora de salida"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )		
			SigSubSType ( "ESRNIndSal" )
		)
	)
)

SignalShape (
	"ESRNIndSalPuntos.s"
	"RENFE Panel Indicadora de salida puntos"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )		
			SigSubSType ( "ESRNIndSalPuntos" )
		)
	)
)

SignalShape (
	"ESRNindagu_EAEC.s"
	"RENFE Panel EAEC"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "s_ESINDEAEC" )
		)
	)
)

SignalShape (
	"ESRNindagu_EAEC_aux.s"
	"RENFE Panel EAEC aux"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "s_ESINDEAEC_aux" )
		)
	)
)

SignalShape (
	"ESRNSEMT.s"
	"RENFE Panel Indicadora Electrica MT Av SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "SPIEMT" )
		)
	)
)

SignalShape (
	"dirID.s"
	"RENFE Lum Dire Izq-Der No poste"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPDID" )
		)
	)
)

SignalShape (
	"dirIF.s"
	"RENFE Lum Dire Izq-Frt No poste"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPDIF" )
		)
	)
)

SignalShape (
	"dirDF.s"
	"RENFE Lum Dire Frn-Der No poste"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPDDF" )
		)
	)
)
