	
	SignalType ( "GIFDESPIVAMASTILAVANZADA_60_D"
		SignalFnType ( INDAGUJAS )
		ORTSScript(MFIA)
		SignalLightTex ( "ia6dtex" )
		Include ( "../Script/Signal/SIGCFG/sigcfg_vel_aprec_GIF.inc" )
	)
	SignalType ( "GIFDESPIVAMASTILAVANZADA_60_I"
		SignalFnType ( INDAGUJAS )
		ORTSScript(MFIA)
		SignalLightTex ( "ia6itex" )
		Include ( "../Script/Signal/SIGCFG/sigcfg_vel_aprec_GIF.inc" )
	)
	
		SignalType ( "GIFIZSPIVAMASTILAVANZADA_60_D"
		SignalFnType ( INDAGUJAS )
		ORTSScript(MFIA)
		SignalLightTex ( "ia6dtex" )
		Include ( "../Script/Signal/SIGCFG/sigcfg_vel_aprec_GIF.inc" )
	)
	SignalType ( "GIFIZSPIVAMASTILAVANZADA_60_I"
		SignalFnType ( INDAGUJAS )
		ORTSScript(MFIA)
		SignalLightTex ( "ia6itex" )
		Include ( "../Script/Signal/SIGCFG/sigcfg_vel_aprec_GIF.inc" )
	)

		SignalType ( "GIFDEPAP70SOLOAPARA"
		SignalFnType ( PPREANUNCIO )
		ORTSScript(PAPAPARA)
		SignalLightTex ( "7PAP" )
		Include ( "../Script/Signal/SIGCFG/sigcfg_preanuncio_GIF.inc" )
	)
	
		SignalType ( "GIFIZPAP70SOLOAPARA"
		SignalFnType ( PPREANUNCIO )
		ORTSScript(PAPAPARA)
		SignalLightTex ( "7PAP" )
		Include ( "../Script/Signal/SIGCFG/sigcfg_preanuncio_GIF.inc" )
	)

	SignalType ( "SPIAI60GIF"
		SignalFnType ( SPEED )
		ORTSScript(SPIA)
		SignalLightTex ( "iaitex" )
		Include ( "../Script/Signal/SIGCFG/sigcfg_vel_ia_GIF.inc" )
	)
	
	SignalType ( "SPIAD60GIF"
		SignalFnType ( SPEED )
		ORTSScript(SPIA)
		SignalLightTex ( "iadtex" )
		Include ( "../Script/Signal/SIGCFG/sigcfg_vel_ia_GIF.inc" )
	)
	