
SignalShape (
	"ESRNindagu_OPAP.s"
	"RENFE Oculto PAP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "OPAP" )
		)
	)
)

SignalShape (
	"ESRNindagu_OLIB.s"
	"RENFE Oculto Senal Liberacion"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "OLIB" )
		)
	)
)

SignalShape (
	"ESRNindagu_I_PREA_SIG_APREC_A_VL.s"
	"RENFE Oculto I PREA a VL Sen Sig APREC"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "s_I_PREA_SIG_APREC_A_VL" )
		)
	)
)

SignalShape (
	"ESRNindagu_I_PREA_SIG_APARA_A_VL.s"
	"RENFE Oculto I PREA a VL Sen Sig APARA"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "s_I_PREA_SIG_APARA_A_VL" )
		)
	)
)

SignalShape (
	"ESRNindagu_I_VL_A_APREC.s"
	"RENFE Oculto de VL a APREC"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "s_I_VL_A_APREC" )
		)
	)
)

SignalShape (
	"ESRNindagu_I_VL_A_VLC.s"
	"RENFE Oculto de VL a VLC"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "s_I_VL_A_VLC" )
		)
	)
)

SignalShape (
	"ESRNindagu_APARADA_INMEDIATA.s"
	"RENFE Oculto de Anuncio Parada Inmediata"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "s_APARADA_INMEDIATA" )
		)
	)
)

SignalShape (
	"ESRNindagu_F_PREA_SIG_PREA.s"
	"RENFE Oculto PREA sig PREA"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "s_F_PREA_SIG_PREA" )
		)
	)
)

SignalShape (
	"ESRNindagu_F_VLC_SIG_VLC.s"
	"RENFE Oculto VLC sig VLC"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "s_F_VLC_SIG_VLC" )
		)
	)
)

SignalShape (
	"ESRNindagu_F_APARA_SIG_APARA.s"
	"RENFE Oculto APARA sig APARA"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "s_F_APARA_SIG_APARA" )
		)
	)
)

SignalShape (
	"ESRNindagu_F_APREC_SIG_APARA.s"
	"RENFE Oculto APREC sig APARA"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "s_F_APREC_SIG_APARA" )
		)
	)
)

SignalShape (
	"ESRNindagu_F_VL.s"
	"RENFE Oculto que fuerza VL si libre"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "s_F_VL" )
		)
	)
)

SignalShape (
	"ESRNindagu_F_PARADA.s"
	"RENFE Oculto que fuerza parada"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "s_F_PARADA" )
		)
	)
)

SignalShape (
	"ESRNindagu_F_REBASE.s"
	"RENFE Oculto que fuerza rebase"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "s_F_REBASE" )
		)
	)
)

SignalShape (
	"ESRNindagu_B_DOSCIENTOS.s"
	"RENFE Oculto VLC sig APREC APARA PREA"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "s_B_DOSCIENTOS" )
		)
	)
)

SignalShape (
	"ESRNindagu_R_DESTELLOS.s"
	"RENFE Oculto rebase auto destellos"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "s_R_DESTELLOS" )
		)
	)
)

SignalShape (
	"ESRNindagu_R_CORtO.s"
	"RENFE Oculto rebase corta distancia"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "s_R_CORTO" )
		)
	)
)
	
SignalShape (
	"ESRNindagu_R_APARADA.s"
	"RENFE Oculto reposo anuncio de parada"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "s_R_APARADA" )
		)
	)
)

SignalShape (
	"ESRNindagu_R_VL.s"
	"RENFE Oculto reposo via libre"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "s_R_VL" )
		)
	)
)

SignalShape (
	"ESRNindagu_M_V_DESV.s"
	"RENFE Oculto marcador via desviada"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "s_M_V_DESV" )
		)
	)
)

SignalShape (
	"ESRNOcul.s"
	"ESRN Señal oculta"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Fixed arm"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ESRNOcul" )
		)
	)
)
