
SignalType ( "LZB"
	SignalFnType ( LZB )
	SignalLightTex ( "ltex" )
	SigFlashDuration ( 0.5 0.5 )
	SignalLights ( 0 )
	SignalDrawStates ( 1
		SignalDrawState ( 0
			"Default"
			DrawLights ( 0 )
		)
	)
	SignalAspects ( 1
		SignalAspect ( CLEAR_2					"Default" 				           )
	)
	SignalNumClearAhead ( 5 )
)
SignalType ( "LZBSTART"
	SignalFnType ( LZB )
	SignalLightTex ( "ltex" )
	SigFlashDuration ( 0.5 0.5 )
	SignalLights ( 0 )
	SignalDrawStates ( 1
		SignalDrawState ( 0
			"Default"
			DrawLights ( 0 )
		)
	)
	SignalAspects ( 1
		SignalAspect ( CLEAR_2					"Default" 				           )
	)
	SignalNumClearAhead ( 5 )
)
SignalType ( "LZBEND"
	SignalFnType ( LZB )
	SignalLightTex ( "ltex" )
	SigFlashDuration ( 0.5 0.5 )
	SignalLights ( 0 )
	SignalDrawStates ( 1
		SignalDrawState ( 0
			"Default"
			DrawLights ( 0 )
		)
	)
	SignalAspects ( 1
		SignalAspect ( STOP_AND_PROCEED					"Default" 				           )
	)
	SignalNumClearAhead ( 5 )
)
