
SignalShape (
	"ESRNindagu_PAP.s"
	"RENFE Panel PAP"
	SignalSubObjs ( 8
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "PAP" )
		)
		SignalSubObj ( 1
			"DECOR"
			"Siguiente Anuncio de Parada"
			SigSubType ( DECOR )
			SignalFlags ( OPTIONAL )
		)
		SignalSubObj ( 2
			"DECOR"
			"Siguiente Anuncio de Precaucion"
			SigSubType ( DECOR )
			SignalFlags ( OPTIONAL )
		)
		SignalSubObj ( 3
			"DECOR"
			"Siguiente Preanuncio de Parada"
			SigSubType ( DECOR )
			SignalFlags ( OPTIONAL )
		)
		SignalSubObj ( 4
			"DECOR"
			"Sumar 10km/h"
			SigSubType ( DECOR )
			SignalFlags ( OPTIONAL )
		)
		SignalSubObj ( 5
			"DECOR"
			"Sumar 20km/h"
			SigSubType ( DECOR )
			SignalFlags ( OPTIONAL )
		)
		SignalSubObj ( 6
			"DECOR"
			"Sumar 40km/h"
			SigSubType ( DECOR )
			SignalFlags ( OPTIONAL )
		)
		SignalSubObj ( 7
			"DECOR"
			"Sumar 80km/h"
			SigSubType ( DECOR )
			SignalFlags ( OPTIONAL )
		)
	)
)

SignalShape (
	"ESRNindagu_SP.s"
	"RENFE Panel Aguja 60 Der Av SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIAD60" )
		)
	)
)

SignalShape (
	"ESRNindagu_SP2.s"
	"RENFE Panel Aguja 60 Izq Av SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIAI60" )
		)
	)
)


SignalShape (
	"ESRNindagu_SP3.s"
	"RENFE Panel Aguja Directa Av SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIAD" )
		)
	)
)

SignalShape (
	"ESRNindagu_SP14.s"
	"RENFE Panel Aguja 20 Derecha Av SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIA20D" )
		)
	)
)

SignalShape (
	"ESRNindagu_SP15.s"
	"RENFE Panel Aguja 20 Izquierda Av SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIA20I" )
		)
	)
)

SignalShape (
	"ESRNindagu_SP4.s"
	"RENFE Panel Aguja 30 Derecha Av SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIA30D" )
		)
	)
)

SignalShape (
	"ESRNindagu_SP5.s"
	"RENFE Panel Aguja 30 Izquierda Av SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIA30I" )
		)
	)
)

SignalShape (
	"ESRNindagu_SP6.s"
	"RENFE Panel Aguja 40 Derecha Av SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIA40D" )
		)
	)
)

SignalShape (
	"ESRNindagu_SP7.s"
	"RENFE Panel Aguja 40 Izquierda Av SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIA40I" )
		)
	)
)

SignalShape (
	"ESRNindagu_SP8.s"
	"RENFE Panel Aguja 50 Derecha Av SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIA50D" )
		)
	)
)

SignalShape (
	"ESRNindagu_SP9.s"
	"RENFE Panel Aguja 50 Izquierda Av SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIA50I" )
		)
	)
)

SignalShape (
	"ESRNindagu_SP16.s"
	"RENFE Panel Aguja 80 Derecha Av SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIA80D" )
		)
	)
)

SignalShape (
	"ESRNindagu_SP17.s"
	"RENFE Panel Aguja 80 Izquierda Av SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIA80I" )
		)
	)
)

SignalShape (
	"ESRNindagu_SP10.s"
	"RENFE Panel Aguja 100 Derecha Av SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIA100D" )
		)
	)
)

SignalShape (
	"ESRNindagu_SP11.s"
	"RENFE Panel Aguja 100 Izquierda Av SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIA100I" )
		)
	)
)

SignalShape (
	"ESRNindagu_SP12.s"
	"RENFE Panel Aguja 160 Derecha Av SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIA160D" )
		)
	)
)

SignalShape (
	"ESRNindagu_SP13.s"
	"RENFE Panel Aguja 160 Izquierda Av SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIA160I" )
		)
	)
)

SignalShape (
	"ESRNindagumastilavanzada_20_d.s"
	"RENFE Panel Aguja 20 Derecha Avanzada SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIVAMASTILAVANZADA_20_D" )
		)
	)
)

SignalShape (
	"ESRNindagumastilavanzada_20_i.s"
	"RENFE Panel Aguja 20 Izquierda Avanzada SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIVAMASTILAVANZADA_20_I" )
		)
	)
)
	
SignalShape (
	"ESRNindagumastilavanzada_40_d.s"
	"RENFE Panel Aguja 40 Derecha Avanzada SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIVAMASTILAVANZADA_40_D" )
		)
	)
)

SignalShape (
	"ESRNindagumastilavanzada_40_i.s"
	"RENFE Panel Aguja 40 Izquierda Avanzada SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIVAMASTILAVANZADA_40_I" )
		)
	)
)

SignalShape (
	"ESRNindagumastilavanzada_45_d.s"
	"RENFE Panel Aguja 45 Derecha Avanzada SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIVAMASTILAVANZADA_45_D" )
		)
	)
)

SignalShape (
	"ESRNindagumastilavanzada_45_i.s"
	"RENFE Panel Aguja 45 Izquierda Avanzada SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIVAMASTILAVANZADA_45_I" )
		)
	)
)

SignalShape (
	"ESRNindagumastilavanzada_50_d.s"
	"RENFE Panel Aguja 50 Derecha Avanzada SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIVAMASTILAVANZADA_50_D" )
		)
	)
)

SignalShape (
	"ESRNindagumastilavanzada_50_i.s"
	"RENFE Panel Aguja 50 Izquierda Avanzada SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIVAMASTILAVANZADA_50_I" )
		)
	)
)

SignalShape (
	"ESRNindagumastilavanzada_60_d.s"
	"RENFE Panel Aguja 60 Derecha Avanzada SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIVAMASTILAVANZADA_60_D" )
		)
	)
)

SignalShape (
	"ESRNindagumastilavanzada_60_i.s"
	"RENFE Panel Aguja 60 Izquierda Avanzada SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIVAMASTILAVANZADA_60_I" )
		)
	)
)

SignalShape (
	"ESRNindagumastilavanzada_100_d.s"
	"RENFE Panel Aguja 100 Derecha Avanzada SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIVAMASTILAVANZADA_100_D" )
		)
	)
)

SignalShape (
	"ESRNindagumastilavanzada_100_i.s"
	"RENFE Panel Aguja 100 Izquierda Avanzada SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIVAMASTILAVANZADA_100_I" )
		)
	)
)

SignalShape (
	"ESRNindagumastilavanzada_160_d.s"
	"RENFE Panel Aguja 160 Derecha Avanzada SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIVAMASTILAVANZADA_160_D" )
		)
	)
)

SignalShape (
	"ESRNindagumastilavanzada_160_i.s"
	"RENFE Panel Aguja 160 Izquierda Avanzada SP"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SPIVAMASTILAVANZADA_160_I" )
		)
	)
)
