
ORTSSignalFunctions ( 39
    ORTSSignalFunctionType ( INDAGUJAS )

    ORTSSignalFunctionType ( OPEDALPN_T )
    ORTSSignalFunctionType ( OLPN_T )
    ORTSSignalFunctionType ( PN_T )
    ORTSSignalFunctionType ( OPN_T )

    ORTSSignalFunctionType ( OLIBERACION )

    ORTSSignalFunctionType ( OPREANUNCIO )
    ORTSSignalFunctionType ( PPREANUNCIO )

    ORTSSignalFunctionType ( I_PREA_SIG_APREC_A_VL )
    ORTSSignalFunctionType ( I_PREA_SIG_APARA_A_VL )
    ORTSSignalFunctionType ( I_VL_A_APREC )
    ORTSSignalFunctionType ( I_VL_A_VLC )

    ORTSSignalFunctionType ( APARADA_INMEDIATA )

    ORTSSignalFunctionType ( F_VL )
    ORTSSignalFunctionType ( F_VLC_SIG_VLC )
    ORTSSignalFunctionType ( F_APARA_SIG_APARA )
    ORTSSignalFunctionType ( F_APREC_SIG_APARA )
    ORTSSignalFunctionType ( F_PARADA )
    ORTSSignalFunctionType ( F_REBASE )

    ORTSSignalFunctionType ( B_DOSCIENTOS )
    ORTSSignalFunctionType ( R_DESTELLOS )
    ORTSSignalFunctionType ( R_APARADA )
    ORTSSignalFunctionType ( R_VL )
    ORTSSignalFunctionType ( R_CORTO )

    ORTSSignalFunctionType ( F_PREA_SIG_PREA )

    ORTSSignalFunctionType ( M_V_DESV )

    ORTSSignalFunctionType ( ASFA )
    ORTSSignalFunctionType ( ETCS )
    ORTSSignalFunctionType ( ETCS_LEVEL )
    ORTSSignalFunctionType ( ETCS_PACKET )
    ORTSSignalFunctionType ( ETCS_CFG )
    ORTSSignalFunctionType ( VELOCIDAD SPEED )
    ORTSSignalFunctionType ( LZB )
    ORTSSignalFunctionType ( ATO )

    ORTSSignalFunctionType ( ESRC_PASO )
    ORTSSignalFunctionType ( ESRC_SALIDA )
    ORTSSignalFunctionType ( ESINDEAEC )
    ORTSSignalFunctionType ( IND_C )
    ORTSSignalFunctionType ( MASTER_ECEAC )
)
ORTSNormalSubtypes( 2
    ORTSNormalSubtype ( PANTALLA_ERTMS )
    ORTSNormalSubtype ( RETROCESO )
)
