
SignalType ( "ASFA_BALIZA_SENAL"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	SigFlashDuration ( 0.5 0.5 )
	ORTSScript (ASFA)
    Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)
SignalType ( "ASFA_BALIZA_PREVIA_SENAL"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	SigFlashDuration ( 0.5 0.5 )
	ORTSScript (ASFA)
    Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)

SignalType ( "ASFA_BALIZA_L7"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	ORTSScript (ASFA)
	SigFlashDuration ( 0.5 0.5 )
    Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)

SignalType ( "ASFA_BALIZA_L1"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	ORTSScript (ASFA)
    Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)

SignalType ( "ASFA_BALIZA_L2"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	SigFlashDuration ( 0.5 0.5 )
	ORTSScript (ASFA)    
	Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)

SignalType ( "ASFA_BALIZA_L3"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	ORTSScript (ASFA)    
	Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)

SignalType ( "ASFA_BALIZA_L4"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	SigFlashDuration ( 0.5 0.5 )
	ORTSScript (ASFA)    
	Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)


SignalType ( "ASFA_BALIZA_L8"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	ORTSScript (ASFA)    
	Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)

SignalType ( "ASFA_BALIZA_PN"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	ORTSScript (ASFA)    
	Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)

SignalType ( "ASFA_BALIZA_PREVIA_Eprima_BLA"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	ORTSScript (ASFA)    
	Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)

SignalType ( "ASFA_BALIZA_PREVIA_PEprima_BLA"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	ORTSScript (ASFA)
	SigFlashDuration ( 0.5 0.5 )    Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)


SignalType ( "ASFA_BALIZA_PN_FASE_2"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	ORTSScript (ASFA)    
	Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)

SignalType ( "ASFA_BALIZA_L9"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	ORTSScript (ASFA)    
	Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)

SignalType ( "ASFA_BALIZA_L10"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	ORTSScript (ASFA)    
	Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)

SignalType ( "ASFA_BALIZA_L11"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	ORTSScript (ASFA)
	SigFlashDuration ( 0.5 0.5 )    Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)


SignalType ( "ASFA_BALIZA_SENAL_FASE_2"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	SigFlashDuration ( 0.5 0.5 )
	ORTSScript (ASFA)    
	Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)
SignalType ( "ASFA_BALIZA_PREVIA_SENAL_FASE_2"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	SigFlashDuration ( 0.5 0.5 )
	ORTSScript (ASFA)    
	Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)

SignalType ( "ASFA_BALIZA_L7_FASE_2"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	ORTSScript (ASFA)
	SigFlashDuration ( 0.5 0.5 )    Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)

SignalType ( "ASFA_BALIZA_L1_FASE_2"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	ORTSScript (ASFA)    
	Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)

SignalType ( "ASFA_BALIZA_L2_FASE_2"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	SigFlashDuration ( 0.5 0.5 )
	ORTSScript (ASFA)    
	Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)

SignalType ( "ASFA_BALIZA_L3_FASE_2"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	ORTSScript (ASFA)    
	Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)

SignalType ( "ASFA_BALIZA_L8_FASE_2"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	ORTSScript (ASFA)    
	Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)


SignalType ( "ASFA_BALIZA_PREVIA_Eprima_BLA_FASE_2"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	ORTSScript (ASFA)    
	Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)

SignalType ( "ASFA_BALIZA_PREVIA_PEprima_BLA_FASE_2"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	ORTSScript (ASFA)
	SigFlashDuration ( 0.5 0.5 )    Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)

SignalType ( "ASFA_BALIZA_L9_FASE_2"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	ORTSScript (ASFA)    
	Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)

SignalType ( "ASFA_BALIZA_L10_FASE_2"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	ORTSScript (ASFA)    
	Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)

SignalType ( "ASFA_BALIZA_L11_FASE_2"
	SignalFnType ( ASFA )
	SignalLightTex ( "ltex" )
	ORTSScript (ASFA)
	SigFlashDuration ( 0.5 0.5 )    Include ( "sigcfg_ocultas.inc" )
	SignalNumClearAhead ( 5 )
)
