
SignalShape (
	"ESRN_Mono4Focos_Pequeno.s"
	"RENFE Lum Mono Pequeño 4 focos VRAB"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP4MSBAB_PQ" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"ESRN_Mono4Focos_Izq_Pequeno.s"
	"RENFE Lum Mono Pequeño 4 focos Izq VRAB"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP4MSBAB_PQ_izq" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"ESRN_Mono3Focos_Pequeno.s"
	"RENFE Lum Mono Pequeño 3 focos Izq VRB"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP3MSBEML_PQ" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"ESRN_Mono3Focos_Izq_Pequeno.s"
	"RENFE Lum Mono Pequeño 3 focos Izq VRB "
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP3MSBEML_PQ_izq" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"ESRN_Mono4Focos.s"
	"RENFE Lum Mono 4 focos VRAB"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP4MSBAB" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"ESRN_Mono4Focos_Izq.s"
	"RENFE Lum Mono 4 focos Izq VRAB"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP4MSBAB_izq" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"mono4luces7.s"
	"RENFE Lum VRB Mono Salida BEM BT BAU BLAB"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP3MSBEM" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"mono4luces7_izq.s"
	"RENFE Lum VRB Mono Salida BEM BT BAU BLAB izq"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP3MSBEM_izq" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"2lucessinamarilloP.s"
	"RENFE Lum 3 focos VR Salida BLA Permisiva"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "SP2VRP" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"2lucessinamarillo.s"
	"RENFE Lum 3 focos VR Salida BLA"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "SP2VR" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"preavanzada.s"
	"RENFE Lum 1 foco V Preavanzada"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "SP1V" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"2lucessinverde.s"
	"RENFE Lum 3 focos RA Entrada Sin Verde"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "SP2RA" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"3luces.s"
	"RENFE Lum 3 focos VRA Intermedia"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP3" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"ESRN_Luminosa_3_focos_Tunel_Izq.s"
	"RENFE Lum 3 focos Tunel Izq VRA Intermedia"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP3" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"ESRN_Luminosa_3_focos_Tunel_Der.s"
	"RENFE Lum 3 focos Tunel Der VRA Intermedia"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP3" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"perm.s"
	"RENFE Lum 3 focos VRA Intermedia Permisiva"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "SP3P" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"3lucesmas1.s"
	"RENFE Lum 3+1 focos VRAB"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP4EBAB" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"ESRN_Luminosa_3+1_focos_Tunel_Izq.s"
	"RENFE Lum 3+1 focos Tunel Izq VRAB"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP4EBAB" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"ESRN_Luminosa_3+1_focos_Tunel_Der.s"
	"RENFE Lum 3+1 focos Tunel Der VRAB"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP4EBAB" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"4luces.s"
	"RENFE Lum 4 focos VRZA Permisiva"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "SP4IBAB" )
			SignalFlags ( JN_LINK )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"4lucesmas1.s"
	"RENFE Lum 5 focos VRZAB"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "SP5EBAB" )
			SignalFlags ( JN_LINK )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"3lucesmas1sinverde.s"
	"RENFE Lum 3 focos RAB Entrada Sin Verde"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP3E" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"mono4luces.s"
	"RENFE Lum Mono 4 focos VRAB"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP4MSBAB" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"mono4luces_izq.s"
	"RENFE Lum Mono 4 focos Izq VRAB"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP4MSBAB_izq" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"mono4luces2.s"
	"RENFE Lum Mono 4 focos RBBB Retroceso"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP4MD" )
		)
	)
)

SignalShape (
	"mono4luces2_izq.s"
	"RENFE Lum Mono 4 focos Izq RBBB Retroceso"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP4MD_izq" )
		)
	)
)

SignalShape (
	"mono2luces.s"
	"RENFE Lum Mono 2 focos RB Maniobras"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP2MB" )
		)
	)
)

SignalShape (
	"mono2focos_pq.s"
	"RENFE Lum Mono 2 focos RB Maniobras Pequeña"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP2MB_pq" )
		)
	)
)

SignalShape (
	"3lucesmas1sinverde2.s"
	"RENFE Lum 3 focos RB Reg Maniobras"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP2M" )
		)
	)
)

SignalShape (
	"SELULED2FOCOSMONOTOPES.s"
	"RENFE Lum Mono 2 focos RR Topera"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SELU2MONOTOPERA" )
		)
	)
)

SignalShape (
	"SELULED2FOCOSMONOTOPES_PQ.s"
	"RENFE Lum Mono 2 focos RR Topera Pequeña"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SELU2MONOTOPERA_PQ" )
		)
	)
)

SignalShape (
	"Cartel_Parada_Absoluta.s"
	"Señal Fija Parada Absoluta Toperas"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "CARTELPARADA" )
		)
	)
)

SignalShape (
	"3lucesinrojo.s"
	"RENFE Lum 3 focos VA Avanzada BLA"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )		
			SigSubSType ( "SP2AV" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"3lucesmas1sinamarillo1.s"
	"RENFE Lum 3+1 focos VRB Salida BLA"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP3SBEM" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"3lucesmas1sinpostetunDER.s"
	"RENFE Lum VRAB Entrada Tunel DER"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP4ETBADDER" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)
SignalShape (
	"3lucesmas1sinpostetunIZQ.s"
	"RENFE Lum VRAB Entrada Tunel IZQ"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP4ETBADIZQ" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)


SignalShape (
	"3lucessinPDER.s"
	"RENFE Lum VRA Tun DER"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "SP3TUNDERSINP" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"3lucessinPIZQ.s"
	"RENFE Lum VRA Tun IZQ"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "SP3TUNIZQSINP" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"3lucesmas1sinpostesinA.s"
	"RENFE Lum VRB Salida BEM BT BAU BLAB SP"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP3SBEMSP" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)

SignalShape (
	"3lucesmas1sinverdesinposte.s"
	"RENFE Lum RAB Entrada No Poste"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP3ESP" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)
SignalShape (
	"3lucesmas1sinposte2.s"
	"RENFE Lum VRAB Salida BAB No Poste"
	SignalSubObjs ( 16
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SignalFlags ( JN_LINK )
			SigSubSType ( "SP4SBABSP" )
		)
		Include ( "sigcfg_head_caracteristicas.inc" )
	)
)
