

SignalAspects ( 7
	SignalAspect ( STOP                        "FF7A"                    SpeedMPH ( 0 )  )
	SignalAspect ( CLEAR_2                        "FF1A"                            )
	SignalAspect ( CLEAR_1                                 "FF2" )
	SignalAspect ( APPROACH_1                                 "FF5A" )
	SignalAspect ( APPROACH_2                              "FF3A" )
	SignalAspect ( APPROACH_3                              "FF4" )
	SignalAspect ( RESTRICTING                               "FF8A" )
	
)
