
SignalDrawStates ( 12
	SignalDrawState ( 0
		"FF7A"
		DrawLights ( 1
			DrawLight ( 0 )
		)
	)
	SignalDrawState ( 1
		"FF5A"
		DrawLights ( 1
			DrawLight ( 1 )
		)
	)
	SignalDrawState ( 2
		"FF2"
		DrawLights ( 1
			DrawLight ( 2   SignalFlags ( FLASHING )  )
		)
	)
	SignalDrawState ( 3
		"FF3A"
		DrawLights ( 2
			DrawLight ( 1 )
			DrawLight ( 2 )
		)
	)
	SignalDrawState ( 4
		"FF1A"
		DrawLights ( 1
			DrawLight ( 2 )
		)
	)
	SignalDrawState ( 5
		"FF8B"
		DrawLights ( 2
			DrawLight ( 0 )
			DrawLight ( 3 )
		)
	)
	SignalDrawState ( 6
		"FF8A"
		DrawLights ( 2
			DrawLight ( 0 )
			DrawLight ( 3 SignalFlags ( FLASHING ) )
		)
	)
	SignalDrawState ( 7
		"FF9"
		DrawLights ( 1
			DrawLight ( 3 )
		)
	)
	SignalDrawState ( 8
		"FF6"
		DrawLights ( 1
			DrawLight ( 1 SignalFlags ( FLASHING ) )
		)
	)
	SignalDrawState ( 9
		"FF4"
		DrawLights ( 1
			DrawLight ( 1 )
		)
	)
	SignalDrawState ( 10
		"FF7B"
		DrawLights ( 1
			DrawLight ( 0 )
		)
	)
	SignalDrawState ( 11
		"FF7I"
		DrawLights ( 1
			DrawLight ( 3 )
		)
	)
)
