
SignalShape (
	"ESRNindagu_MASTER_EAEC.s"
	"RENFE MASTER ECEAC"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "s_MASTER_ECEAC" )
		)
	)
)

SignalShape (
	"ESRN_RC_PASO.s"
	"RENFE RC para dar señal de paso"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "s_ESRC_PASO" )
		)
	)
)

SignalShape (
	"ESRN_RC_PASO_aux.s"
	"RENFE RC para dar señal de paso aux"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "s_ESRC_PASO_aux" )
		)
	)
)

SignalShape (
	"ESRN_RC_SALIDA.s"
	"RENFE RC para dar señal de MT"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "s_ESRC_SALIDA" )
		)
	)
)

SignalShape (
	"ESRN_RC_SALIDA_aux.s"
	"RENFE RC para dar señal de MT aux"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "s_ESRC_SALIDA_aux" )
		)
	)
)

SignalShape (
	"PostedC.s"
	"RENFE Cartelon C"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "s_ESCARTELONC" )
		)
	)
)
