
SignalShape (
	"oculta_parada_ato.s"
	"Punto Parada ATO Doble"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "PARADA_ATO" )
		)
	)
)
SignalShape (
	"oculta_parada_ato_simple.s"
	"Punto Parada ATO Simple"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "PARADA_ATO_SIMPLE" )
		)
	)
)
	