
SignalType ( "PARADA_ATO"
	SignalFnType ( ATO )
	SignalLightTex ( "ltex" )
	SignalLights ( 0 )
	SignalDrawStates ( 1
		SignalDrawState ( 0
			"Unlit"
			DrawLights ( 0 )
		)
	)
	SignalAspects ( 1
		SignalAspect ( CLEAR_2				"Unlit" 				         )
	)
	SignalNumClearAhead ( 0 )
)
SignalType ( "PARADA_ATO_SIMPLE"
	SignalFnType ( ATO )
	SignalLightTex ( "ltex" )
	SignalLights ( 0 )
	SignalDrawStates ( 1
		SignalDrawState ( 0
			"Unlit"
			DrawLights ( 0 )
		)
	)
	SignalAspects ( 1
		SignalAspect ( CLEAR_2				"Unlit" 				         )
	)
	SignalNumClearAhead ( 0 )
)
