
LightTextures ( 58
	LightTex ( "RCPASOtex"			"RCPASO.ace"			0 0  -1 1 )
	LightTex ( "RCSALIDAtex"			"RCSALIDA.ace"			0 0  -1 1 )
	LightTex ( "RCPARADAtex"			"RCPARADA.ace"				0 0  -1 1 )
	LightTex ( "EAtex"			"EA.ace"			0 0  -1 1 )
	LightTex ( "ECtex"			"EC.ace"			0 0  -1 1 )
	LightTex ( "Ctex"			"C.ace"				0 0  -1 1 )
	LightTex ( "ltex"			"SigLight.ace"		0 0  1 1 )
	LightTex ( "iePNtex"		"PN.ace"			0 0 -1 1 )
	LightTex ( "ieOPNtex"		"OPN.ace"			0 0 -1 1 )
	LightTex ( "iadtex"			"6d.ace"			0 0 -1 1 )
	LightTex ( "5PAP"			"5PAP.ace"			0 0 -1 1 )
	LightTex ( "6PAP"			"6PAP.ace"			0 0 -1 1 )
	LightTex ( "7PAP"			"7PAP.ace"			0 0 -1 1 )
	LightTex ( "8PAP"			"8PAP.ace"			0 0 -1 1 )
	LightTex ( "9PAP"			"9PAP.ace"			0 0 -1 1 )
	LightTex ( "10PAP"			"10PAP.ace"			0 0 -1 1 )
	LightTex ( "11PAP"			"11PAP.ace"			0 0 -1 1 )
	LightTex ( "12PAP"			"12PAP.ace"			0 0 -1 1 )
	LightTex ( "13PAP"			"13PAP.ace"			0 0 -1 1 )
	LightTex ( "14PAP"			"14PAP.ace"			0 0 -1 1 )
	LightTex ( "15PAP"			"15PAP.ace"			0 0 -1 1 )
	LightTex ( "iaitex"			"6i.ace"			0 0 -1 1 )
	LightTex ( "iavdtex"		"vd.ace"			0 0 -1 1 )
	LightTex ( "ia3dtex"		"3d.ace"			0 0 -1 1 )
	LightTex ( "ia3itex"		"3i.ace"			0 0 -1 1 )
	LightTex ( "ia4dtex"		"4d.ace"			0 0 -1 1 )
	LightTex ( "ia4itex"		"4i.ace"			0 0 -1 1 )
	LightTex ( "ia45dtex"		"45d.ace"			0 0 -1 1 )
	LightTex ( "ia45itex"		"45i.ace"			0 0 -1 1 )
	LightTex ( "ia5dtex"		"5d.ace"			0 0 -1 1 )
	LightTex ( "ia5itex"		"5i.ace"			0 0 -1 1 )
	LightTex ( "ia6dtex"		"6d.ace"			0 0 -1 1 )
	LightTex ( "ia6itex"		"6i.ace"			0 0 -1 1 )
	LightTex ( "ia10dtex"		"10d.ace"			0 0 -1 1 )
	LightTex ( "ia10itex"		"10i.ace"			0 0 -1 1 )
	LightTex ( "iadAtex"		"ID_A.ace"			0 0 -1 1 )
	LightTex ( "iadCtex"		"ID_C.ace"			0 0 -1 1 )
	LightTex ( "iadICtex"		"ID_IC.ace"			0 0 -1 1 )
	LightTex ( "iadBPGtex"		"ID_BPG.ace"		0 0 -1 1 )
	LightTex ( "iadBRtex"		"ID_BR.ace"			0 0 -1 1 )
	LightTex ( "iadARtex"		"ID_AR.ace"			0 0 -1 1 )
	LightTex ( "iadBRStex"		"ID_BRS.ace"		0 0 -1 1 )
	LightTex ( "iadStex"		"ID_S.ace"			0 0 -1 1 )
	LightTex ( "iadSStex"		"ID_SS.ace"			0 0 -1 1 )
	LightTex ( "iadGtex"		"ID_G.ace"			0 0 -1 1 )
	LightTex ( "iadGEtex"		"ID_GE.ace"			0 0 -1 1 )
	LightTex ( "iadPStex"		"ID_PS.ace"			0 0 -1 1 )
	LightTex ( "iadEtex"		"ID_E.ace"			0 0 -1 1 )
	LightTex ( "iadOtex"		"ID_O.ace"			0 0 -1 1 )
	LightTex ( "iadORtex"		"ID_OR.ace"			0 0 -1 1 )
	LightTex ( "iadPtex"		"ID_P.ace"			0 0 -1 1 )
	LightTex ( "ieMTtex"		"MT.ace"			0 0 -1 1 )
	LightTex ( "indsaltex"		"ESRNIndS.ace"		0 0 1 1 )
	LightTex ( "indsaltexPuntos" "ESRNIndSPuntos.ace"	0 0 1 1 )
	LightTex ( "ltex2"			"SigLight2.ace"		0 0 1 1 )
	LightTex ( "IND_EA"			"IND_EA.ace"		0 0 1 1 )
	LightTex ( "IND_EC" 		"IND_EC.ace"		0 0 1 1 )
	LightTex ( "ltexLED"        "SigLightLED.ace"         0 0 1 1)
)


LightsTab ( 8
	LightsTabEntry (
		"Red Light"
		colour ( 240 195 30 39 )
	)
	LightsTabEntry (
		"Amber Light"
		colour ( 255 255 155 0 )
	)
	LightsTabEntry (
		"Green Light"
		colour ( 255 79 186 130 )
	)
	LightsTabEntry (
		"White Light"
		colour ( 255 255 255 191 )
	)
	LightsTabEntry (
		"Violet Light"
		colour ( 255 96 128 255 )
	)
	LightsTabEntry (
		"White Light C"
		colour ( 255 255 255 255 )
	)
	LightsTabEntry (
		"RC Light"
		colour ( 255 150 100 100 )
	)
	LightsTabEntry (
		"Blue Light"
		colour ( 255 0 120 255 )
	)
)
