
SignalShape (
	"ESRNASFA_PIE.s"
	"RENFE Baliza ASFA PIE"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_SENAL" )
		)
	)
)

SignalShape (
	"ESRNASFA_PIE_FASE_2.s"
	"RENFE Baliza ASFA PIE Fase 2"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_SENAL_FASE_2" )
		)
	)
)

SignalShape (
	"ESRNASFA_PRE.s"
	"RENFE Baliza ASFA PRE"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_PREVIA_SENAL" )
		)
	)
)
SignalShape (
	"ESRNASFA_PRE_FASE_2.s"
	"RENFE Baliza ASFA PRE Fase 2"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_PREVIA_SENAL_FASE_2" )
		)
	)
)

SignalShape (
	"ESRNASFA_PRE_BLA.s"
	"RENFE Baliza ASFA PRE AVANZADA BLA"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_PREVIA_Eprima_BLA" )
		)
	)
)

SignalShape (
	"ESRNASFA_PRE_BLA_FASE_2.s"
	"RENFE Baliza ASFA PRE AVANZADA BLA Fase 2"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_PREVIA_Eprima_BLA_FASE_2" )
		)
	)
)
SignalShape (
	"ESRNASFA_PRE_PBLA.s"
	"RENFE Baliza ASFA PRE PREAVANZADA BLA"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_PREVIA_PEprima_BLA" )
		)
	)
)

SignalShape (
	"ESRNASFA_PRE_PBLA_FASE_2.s"
	"RENFE Baliza ASFA PRE PREAVANZADA BLA Fase 2"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_PREVIA_PEprima_BLA_FASE_2" )
		)
	)
)
SignalShape (
	"ESRNASFA_L1.s"
	"RENFE Baliza ASFA L1"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_L1" )
		)
	)
)

SignalShape (
	"ESRNASFA_L1_FASE_2.s"
	"RENFE Baliza ASFA L1 Fase 2"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_L1_FASE_2" )
		)
	)
)
SignalShape (
	"ESRNASFA_L2.s"
	"RENFE Baliza ASFA L2"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_L2" )
		)
	)
)
SignalShape (
	"ESRNASFA_L2_FASE_2.s"
	"RENFE Baliza ASFA L2 Fase 2"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_L2_FASE_2" )
		)
	)
)

SignalShape (
	"ESRNASFA_L3.s"
	"RENFE Baliza ASFA L3"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_L3" )
		)
	)
)
SignalShape (
	"ESRNASFA_L3_FASE_2.s"
	"RENFE Baliza ASFA L3 Fase 2"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_L3_FASE_2" )
		)
	)
)

SignalShape (
	"ESRNASFA_L4_AV.s"
	"RENFE Baliza ASFA L4 AV"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_L4" )
		)
	)
)

SignalShape (
	"ESRNASFA_L8.s"
	"RENFE Baliza ASFA L8"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_L8" )
		)
	)
)

SignalShape (
	"ESRNASFA_L8_FASE_2.s"
	"RENFE Baliza ASFA L8 Fase 2"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_L8_FASE_2" )
		)
	)
)
SignalShape (
	"ESRNASFA_L7.s"
	"RENFE Baliza ASFA L7"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_L7" )
		)
	)
)
SignalShape (
	"ESRNASFA_L7_FASE_2.s"
	"RENFE Baliza ASFA L7 Fase 2"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_L7_FASE_2" )
		)
	)
)

SignalShape (
	"ESRNASFA_PN.s"
	"RENFE Baliza ASFA SPN"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_PN" )
		)
	)
)


SignalShape (
	"ESRNASFA_PN_FASE_2.s"
	"RENFE Baliza ASFA SPN FASE 2"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_PN_FASE_2" )
		)
	)
)

SignalShape (
	"ESRNASFA_L9.s"
	"RENFE Baliza ASFA L9"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_L9" )
		)
	)
)

	SignalShape (
	"ESRNASFA_L9_FASE_2.s"
	"RENFE Baliza ASFA L9 Fase 2"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_L9_FASE_2" )
		)
	)
)

	SignalShape (
	"ESRNASFA_L9_ST.s"
	"RENFE Baliza ASFA L9 Sin Topes"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_L9" )
		)
	)
)

SignalShape (
	"ESRNASFA_L10.s"
	"RENFE Baliza ASFA L10"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_L10" )
		)
	)
)

SignalShape (
	"ESRNASFA_L11.s"
	"RENFE Baliza ASFA L11"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_L11" )
		)
	)
)


SignalShape (
	"ESRNASFA_L10_FASE_2.s"
	"RENFE Baliza ASFA L10 Fase 2"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_L10_FASE_2" )
		)
	)
)

SignalShape (
	"ESRNASFA_L11_FASE_2.s"
	"RENFE Baliza ASFA L11 Fase 2"
	SignalSubObjs ( 1
		SignalSubObj ( 0
			"HEAD1"
			"Signal Head 1"
			SigSubType ( SIGNAL_HEAD )
			SigSubSType ( "ASFA_BALIZA_L11_FASE_2" )
		)
	)
)
