
	SignalShape (
		"GIFPADEPAP7.s"
		"RENFE Panel GIF DE PAP70 SIG EN APARA"
		SignalSubObjs ( 1
			SignalSubObj ( 0
				"HEAD1"
				"Signal Head 1"
				SigSubType ( SIGNAL_HEAD )
				SigSubSType ( "GIFDEPAP70SOLOAPARA" )
			)
		)
	)
	
	
	SignalShape (
		"GIFPAIZPAP7.s"
		"RENFE Panel GIF IZ PAP70 SIG EN APARA"
		SignalSubObjs ( 1
			SignalSubObj ( 0
				"HEAD1"
				"Signal Head 1"
				SigSubType ( SIGNAL_HEAD )
				SigSubSType ( "GIFIZPAP70SOLOAPARA" )
			)
		)
	)
	
		SignalShape (
		"GIFIZ60D2.s"
		"GIF Panel Aguja Izquierda 60 Der Av SP"
		SignalSubObjs ( 1
			SignalSubObj ( 0
				"HEAD1"
				"Signal Head 1"
				SigSubType ( SIGNAL_HEAD )
				SignalFlags ( JN_LINK )
				SigSubSType ( "SPIAD60GIF" )
			)
		)
	)

	SignalShape (
		"GIFIZ60I2.s"
		"GIF Panel Aguja Izquierda 60 Izq Av SP"
		SignalSubObjs ( 1
			SignalSubObj ( 0
				"HEAD1"
				"Signal Head 1"
				SigSubType ( SIGNAL_HEAD )
				SignalFlags ( JN_LINK )
				SigSubSType ( "SPIAI60GIF" )
			)
		)
	)

		SignalShape (
		"GIFDE60D2.s"
		"GIF Panel Aguja Derecha 60 Der Av SP"
		SignalSubObjs ( 1
			SignalSubObj ( 0
				"HEAD1"
				"Signal Head 1"
				SigSubType ( SIGNAL_HEAD )
				SignalFlags ( JN_LINK )
				SigSubSType ( "SPIAD60GIF" )
			)
		)
	)

	SignalShape (
		"GIFDE60I2.s"
		"GIF Panel Aguja Derecha 60 Izq Av SP"
		SignalSubObjs ( 1
			SignalSubObj ( 0
				"HEAD1"
				"Signal Head 1"
				SigSubType ( SIGNAL_HEAD )
				SignalFlags ( JN_LINK )
				SigSubSType ( "SPIAI60GIF" )
			)
		)
	)


	
	SignalShape (
		"GIFIZ60D.s"
		"GIF IZ Panel Aguja 60 Derecha Avanzada SP"
		SignalSubObjs ( 1
			SignalSubObj ( 0
				"HEAD1"
				"Signal Head 1"
				SigSubType ( SIGNAL_HEAD )
				SignalFlags ( JN_LINK )
				SigSubSType ( "GIFIZSPIVAMASTILAVANZADA_60_D" )
			)
		)
	)

	SignalShape (
		"GIFIZ60I.s"
		"GIF IZ Panel Aguja 60 Izquierda Avanzada SP"
		SignalSubObjs ( 1
			SignalSubObj ( 0
				"HEAD1"
				"Signal Head 1"
				SigSubType ( SIGNAL_HEAD )
				SignalFlags ( JN_LINK )
				SigSubSType ( "GIFIZSPIVAMASTILAVANZADA_60_I" )
			)
		)
	)
	SignalShape (
		"GIFDE60D.s"
		"GIF DE Panel Aguja 60 Derecha Avanzada SP"
		SignalSubObjs ( 1
			SignalSubObj ( 0
				"HEAD1"
				"Signal Head 1"
				SigSubType ( SIGNAL_HEAD )
				SignalFlags ( JN_LINK )
				SigSubSType ( "GIFDESPIVAMASTILAVANZADA_60_D" )
			)
		)
	)

	SignalShape (
		"GIFDE60I.s"
		"GIF DE Panel Aguja 60 Izquierda Avanzada SP"
		SignalSubObjs ( 1
			SignalSubObj ( 0
				"HEAD1"
				"Signal Head 1"
				SigSubType ( SIGNAL_HEAD )
				SignalFlags ( JN_LINK )
				SigSubSType ( "GIFDESPIVAMASTILAVANZADA_60_I" )
			)
		)
	)
